# Generated by Django 5.0.2 on 2024-02-22 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accomodation',
            fields=[
                ('acc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=20)),
                ('hotel_cno', models.IntegerField()),
                ('hotel_price_per_night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transportation',
            fields=[
                ('transport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transportation_type', models.CharField(max_length=10)),
                ('pick_date', models.DateField()),
                ('drop_date', models.DateField()),
                ('pick_address', models.CharField(max_length=25)),
                ('drop_address', models.CharField(max_length=25)),
                ('transport_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=3)),
                ('gender', models.CharField(max_length=1)),
                ('contact_no', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('package_id', models.IntegerField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=15)),
                ('package_description', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
                ('package_price', models.IntegerField()),
                ('P_acc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dempapp.accomodation')),
                ('p_transport_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dempapp.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_start_date', models.DateField()),
                ('book_end_date', models.DateField()),
                ('number_of_person', models.IntegerField()),
                ('book_package_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dempapp.package')),
                ('book_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dempapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='reviews_and_ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('r_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dempapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('pay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_payment', models.IntegerField()),
                ('payment_type', models.CharField(max_length=10)),
                ('p_book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dempapp.booking')),
                ('p_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dempapp.user')),
            ],
        ),
    ]
