# Generated by Django 5.0.3 on 2024-03-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='photo',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
