# Generated by Django 5.0.3 on 2024-03-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempapp', '0002_package_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='day1',
            field=models.CharField(default='nice', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='day2',
            field=models.CharField(default='nice', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='day3',
            field=models.CharField(default='nice', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='day4',
            field=models.CharField(default='nice', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='day5',
            field=models.CharField(default='nice', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='day6',
            field=models.CharField(default='nice', max_length=200),
        ),
    ]
