# Generated by Django 5.0.3 on 2024-03-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempapp', '0003_package_day1_package_day2_package_day3_package_day4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='day1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='day2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='day3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='day4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='day5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='day6',
            field=models.TextField(),
        ),
    ]
